// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Arm.proto

#ifndef PROTOBUF_Arm_2eproto__INCLUDED
#define PROTOBUF_Arm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace haptix {
namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Arm_2eproto();
void protobuf_AssignDesc_Arm_2eproto();
void protobuf_ShutdownFile_Arm_2eproto();

class Arm;

// ===================================================================

class Arm : public ::google::protobuf::Message {
 public:
  Arm();
  virtual ~Arm();

  Arm(const Arm& from);

  inline Arm& operator=(const Arm& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Arm& default_instance();

  void Swap(Arm* other);

  // implements Message ----------------------------------------------

  Arm* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Arm& from);
  void MergeFrom(const Arm& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline double pos() const;
  inline void set_pos(double value);

  // required double vel = 2;
  inline bool has_vel() const;
  inline void clear_vel();
  static const int kVelFieldNumber = 2;
  inline double vel() const;
  inline void set_vel(double value);

  // @@protoc_insertion_point(class_scope:haptix.comm.Arm)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_vel();
  inline void clear_has_vel();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double pos_;
  double vel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Arm_2eproto();
  friend void protobuf_AssignDesc_Arm_2eproto();
  friend void protobuf_ShutdownFile_Arm_2eproto();

  void InitAsDefaultInstance();
  static Arm* default_instance_;
};
// ===================================================================


// ===================================================================

// Arm

// required double pos = 1;
inline bool Arm::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Arm::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Arm::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Arm::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline double Arm::pos() const {
  return pos_;
}
inline void Arm::set_pos(double value) {
  set_has_pos();
  pos_ = value;
}

// required double vel = 2;
inline bool Arm::has_vel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Arm::set_has_vel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Arm::clear_has_vel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Arm::clear_vel() {
  vel_ = 0;
  clear_has_vel();
}
inline double Arm::vel() const {
  return vel_;
}
inline void Arm::set_vel(double value) {
  set_has_vel();
  vel_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm
}  // namespace haptix

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Arm_2eproto__INCLUDED
