// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMsg.proto

#ifndef PROTOBUF_TestMsg_2eproto__INCLUDED
#define PROTOBUF_TestMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace haptix {
namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TestMsg_2eproto();
void protobuf_AssignDesc_TestMsg_2eproto();
void protobuf_ShutdownFile_TestMsg_2eproto();

class TestMsg;

// ===================================================================

class TestMsg : public ::google::protobuf::Message {
 public:
  TestMsg();
  virtual ~TestMsg();

  TestMsg(const TestMsg& from);

  inline TestMsg& operator=(const TestMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMsg& default_instance();

  void Swap(TestMsg* other);

  // implements Message ----------------------------------------------

  TestMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMsg& from);
  void MergeFrom(const TestMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mydata = 1;
  inline bool has_mydata() const;
  inline void clear_mydata();
  static const int kMydataFieldNumber = 1;
  inline const ::std::string& mydata() const;
  inline void set_mydata(const ::std::string& value);
  inline void set_mydata(const char* value);
  inline void set_mydata(const char* value, size_t size);
  inline ::std::string* mutable_mydata();
  inline ::std::string* release_mydata();
  inline void set_allocated_mydata(::std::string* mydata);

  // required double mydouble = 2;
  inline bool has_mydouble() const;
  inline void clear_mydouble();
  static const int kMydoubleFieldNumber = 2;
  inline double mydouble() const;
  inline void set_mydouble(double value);

  // @@protoc_insertion_point(class_scope:haptix.comm.TestMsg)
 private:
  inline void set_has_mydata();
  inline void clear_has_mydata();
  inline void set_has_mydouble();
  inline void clear_has_mydouble();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mydata_;
  double mydouble_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_TestMsg_2eproto();
  friend void protobuf_AssignDesc_TestMsg_2eproto();
  friend void protobuf_ShutdownFile_TestMsg_2eproto();

  void InitAsDefaultInstance();
  static TestMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// TestMsg

// required string mydata = 1;
inline bool TestMsg::has_mydata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMsg::set_has_mydata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMsg::clear_has_mydata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMsg::clear_mydata() {
  if (mydata_ != &::google::protobuf::internal::kEmptyString) {
    mydata_->clear();
  }
  clear_has_mydata();
}
inline const ::std::string& TestMsg::mydata() const {
  return *mydata_;
}
inline void TestMsg::set_mydata(const ::std::string& value) {
  set_has_mydata();
  if (mydata_ == &::google::protobuf::internal::kEmptyString) {
    mydata_ = new ::std::string;
  }
  mydata_->assign(value);
}
inline void TestMsg::set_mydata(const char* value) {
  set_has_mydata();
  if (mydata_ == &::google::protobuf::internal::kEmptyString) {
    mydata_ = new ::std::string;
  }
  mydata_->assign(value);
}
inline void TestMsg::set_mydata(const char* value, size_t size) {
  set_has_mydata();
  if (mydata_ == &::google::protobuf::internal::kEmptyString) {
    mydata_ = new ::std::string;
  }
  mydata_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TestMsg::mutable_mydata() {
  set_has_mydata();
  if (mydata_ == &::google::protobuf::internal::kEmptyString) {
    mydata_ = new ::std::string;
  }
  return mydata_;
}
inline ::std::string* TestMsg::release_mydata() {
  clear_has_mydata();
  if (mydata_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mydata_;
    mydata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TestMsg::set_allocated_mydata(::std::string* mydata) {
  if (mydata_ != &::google::protobuf::internal::kEmptyString) {
    delete mydata_;
  }
  if (mydata) {
    set_has_mydata();
    mydata_ = mydata;
  } else {
    clear_has_mydata();
    mydata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required double mydouble = 2;
inline bool TestMsg::has_mydouble() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMsg::set_has_mydouble() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMsg::clear_has_mydouble() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMsg::clear_mydouble() {
  mydouble_ = 0;
  clear_has_mydouble();
}
inline double TestMsg::mydouble() const {
  return mydouble_;
}
inline void TestMsg::set_mydouble(double value) {
  set_has_mydouble();
  mydouble_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm
}  // namespace haptix

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TestMsg_2eproto__INCLUDED
