# Button:
#   Motor Name, Increment

# e.g.

-:
  command_name: 'motor_little_ab_ad'
  increment: 0.05

_:
  command_name: 'motor_little_ab_ad'
  increment: -0.05

p:
  command_name: 'motor_little'
  increment: 0.05

P:
  command_name: 'motor_little'
  increment: -0.05

0:
  command_name: 'motor_ring_ab_ad'
  increment: 0.05

):
  command_name: 'motor_ring_ab_ad'
  increment: -0.05

o:
  command_name: 'motor_ring'
  increment: 0.05

O:
  command_name: 'motor_ring'
  increment: -0.05

9:
  command_name: 'motor_middle_ab_ad'
  increment: 0.05

(:
  command_name: 'motor_middle_ab_ad'
  increment: -0.05

i:
  command_name: 'motor_middle'
  increment: 0.05

I:
  command_name: 'motor_middle'
  increment: -0.05

8:
  command_name: 'motor_index_ab_ad'
  increment: 0.05

'*':
  command_name: 'motor_index_ab_ad'
  increment: -0.05

u:
  command_name: 'motor_index'
  increment: 0.05

U:
  command_name: 'motor_index'
  increment: -0.05

7:
  command_name: 'motor_thumb_cmc_ab_ad'
  increment: 0.05

'&':
  command_name: 'motor_thumb_cmc_ab_ad'
  increment: -0.05

6:
  command_name: 'motor_thumb_cmc_fe'
  increment: 0.05

^:
  command_name: 'motor_thumb_cmc_fe'
  increment: -0.05

y:
  command_name: 'motor_thumb'
  increment: 0.05

Y:
  command_name: 'motor_thumb'
  increment: -0.05

k:
  command_name: 'motor_wrist_rot'
  increment: 0.05

K:
  command_name: 'motor_wrist_rot'
  increment: -0.05

l:
  command_name: 'motor_wrist_dev'
  increment: 0.05

L:
  command_name: 'motor_wrist_dev'
  increment: -0.05

;:
  command_name: 'motor_wrist_fe'
  increment: 0.05

::
  command_name: 'motor_wrist_fe'
  increment: -0.05

w:
  command_name: 'arm_pos_x'
  increment: 0.025

s:
  command_name: 'arm_pos_x'
  increment: -0.025

a:
  command_name: 'arm_pos_y'
  increment: 0.025

d:
  command_name: 'arm_pos_y'
  increment: -0.025

q:
  command_name: 'arm_pos_z'
  increment: 0.025

e:
  command_name: 'arm_pos_z'
  increment: -0.025

W:
  command_name: 'arm_rot_x'
  increment: 0.025

S:
  command_name: 'arm_rot_x'
  increment: -0.025

A:
  command_name: 'arm_rot_y'
  increment: 0.025

D:
  command_name: 'arm_rot_y'
  increment: -0.025

Q:
  command_name: 'arm_rot_z'
  increment: 0.025

E:
  command_name: 'arm_rot_z'
  increment: -0.025

