motor_wrist_rot: 0
motor_wrist_dev: 1
motor_wrist_fe: 2
motor_index: 3
motor_middle: 4
motor_ring: 5
motor_little: 6
motor_thumb_cmc_fe: 7
motor_thumb_mcp: 8
motor_thumb_dip: 9
motor_thumb_cmc_ab_ad: 10
motor_index_ab_ad: 11
motor_little_ab_ad: 12
motor_ring_ab_ad: 13
motor_middle_ab_ad: 14
