motor_wrist_rot: 0
motor_wrist_dev: 1
motor_wrist_fe: 2
motor_index: 3
motor_little: 4
motor_middle: 5
motor_thumb_cmc_ab_ad: 6
motor_little_ab_ad: 7
motor_ring_ab_ad: 8
motor_middle_ab_ad: 9
motor_index_ab_ad: 10
motor_thumb_cmc_fe: 11
motor_ring: 12
motor_thumb_mcp: 13
motor_thumb_dip: 14
