motor_wrist_rot: 0
motor_wrist_dev: 1
motor_wrist_fe: 2
motor_index_dip: 3
motor_index_mcp: 4
motor_index_pip: 5
motor_little_dip: 6
motor_little_mcp: 7
motor_little_pip: 8
motor_middle_dip: 9
motor_middle_mcp: 10
motor_middle_pip: 11
motor_thumb_cmc_ab_ad: 12
motor_little_ab_ad: 13
motor_ring_ab_ad: 14
motor_middle_ab_ad: 15
motor_index_ab_ad: 16
motor_thumb_cmc_fe: 17
motor_ring_dip: 18
motor_ring_mcp: 19
motor_ring_pip: 20
motor_thumb_mcp: 21
motor_thumb_dip: 22
