motor_little_ab_ad:    17
motor_ring_ab_ad:      16
motor_middle_ab_ad:    15
motor_index_ab_ad:     14
motor_thumb_cmc_ab_ad: 13
motor_thumb_cmc_fe:    12
motor_little: 8
motor_ring:   7
motor_middle: 6
motor_index:  5
motor_thumb_mcp:  4
motor_thumb_dip:  3
motor_wrist_rot:  2
motor_wrist_dev:  1
motor_wrist_fe:   0
