// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Arm.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "haptix/comm/Arm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace haptix {
namespace comm {

namespace {

const ::google::protobuf::Descriptor* Arm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Arm_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Arm_2eproto() {
  protobuf_AddDesc_Arm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Arm.proto");
  GOOGLE_CHECK(file != NULL);
  Arm_descriptor_ = file->message_type(0);
  static const int Arm_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arm, pos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arm, vel_),
  };
  Arm_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Arm_descriptor_,
      Arm::default_instance_,
      Arm_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arm, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arm, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Arm));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Arm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Arm_descriptor_, &Arm::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Arm_2eproto() {
  delete Arm::default_instance_;
  delete Arm_reflection_;
}

void protobuf_AddDesc_Arm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tArm.proto\022\013haptix.comm\"\037\n\003Arm\022\013\n\003pos\030\001"
    " \002(\001\022\013\n\003vel\030\002 \002(\001", 57);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Arm.proto", &protobuf_RegisterTypes);
  Arm::default_instance_ = new Arm();
  Arm::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Arm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Arm_2eproto {
  StaticDescriptorInitializer_Arm_2eproto() {
    protobuf_AddDesc_Arm_2eproto();
  }
} static_descriptor_initializer_Arm_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Arm::kPosFieldNumber;
const int Arm::kVelFieldNumber;
#endif  // !_MSC_VER

Arm::Arm()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Arm::InitAsDefaultInstance() {
}

Arm::Arm(const Arm& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Arm::SharedCtor() {
  _cached_size_ = 0;
  pos_ = 0;
  vel_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Arm::~Arm() {
  SharedDtor();
}

void Arm::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Arm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Arm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Arm_descriptor_;
}

const Arm& Arm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Arm_2eproto();
  return *default_instance_;
}

Arm* Arm::default_instance_ = NULL;

Arm* Arm::New() const {
  return new Arm;
}

void Arm::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    pos_ = 0;
    vel_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Arm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double pos = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pos_)));
          set_has_pos();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_vel;
        break;
      }

      // required double vel = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_vel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vel_)));
          set_has_vel();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Arm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required double pos = 1;
  if (has_pos()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->pos(), output);
  }

  // required double vel = 2;
  if (has_vel()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->vel(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Arm::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required double pos = 1;
  if (has_pos()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->pos(), target);
  }

  // required double vel = 2;
  if (has_vel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->vel(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Arm::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double pos = 1;
    if (has_pos()) {
      total_size += 1 + 8;
    }

    // required double vel = 2;
    if (has_vel()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Arm::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Arm* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Arm*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Arm::MergeFrom(const Arm& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_pos()) {
      set_pos(from.pos());
    }
    if (from.has_vel()) {
      set_vel(from.vel());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Arm::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Arm::CopyFrom(const Arm& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Arm::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Arm::Swap(Arm* other) {
  if (other != this) {
    std::swap(pos_, other->pos_);
    std::swap(vel_, other->vel_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Arm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Arm_descriptor_;
  metadata.reflection = Arm_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm
}  // namespace haptix

// @@protoc_insertion_point(global_scope)
