find_program(MKOCTFILE mkoctfile)

if (MKOCTFILE)
    set(OCTAVE_SUPPORT_FOUND TRUE)
    message(STATUS "Octave found. mkoctfile at ${MKOCTFILE}")
else()
    set(OCTAVE_SUPPORT_FOUND FALSE)
    message(STATUS "Octave not found (unable to locate mkoctfile)")
    BUILD_WARNING("Octave not found. Not generating octave bindings")
endif()
